#!/bin/bash

# ===============================================
# Global Configuration
# ===============================================
CONFIG_FILE="$HOME/.prospermedical_tools_config"


# Top-level environment variables
declare -a GLOBAL_ENVS_ARRAY=(
    "AWS_REGION"
)

# EC2 environment variables
declare -a EC2_ENVS_ARRAY=()








# ===============================================
# Processes
# ===============================================
show_correct_sintax(){
    echo "Usage: ec2t [OPTION] [ARGUMENT]"
    echo ""
    echo "Options:"
    echo "  --get-id           Get the ID of the specified EC2 instance NAME."
    echo "  --get-name         Get the NAME of the specified EC2 instance ID."
    echo "  --ssm-connect      Connect to the specified EC2 instance name via SSM."
    echo "  --reset-env        Reset all stored environment variables."
    echo ""
    echo "Arguments:"
    echo "  [Instance name]    For --get-id or --ssm-connect option."
    echo "  [Instance id]      For --get-name option."
    echo ""
}

validate_option(){
    local valid_options=(
        "--get-id"
        "--get-name"
        "--ssm-connect"
        "--reset-env"
    )

    for opt in "${valid_options[@]}"; do
        if [[ $opt = $1 ]]; then
            return 0
        fi
    done

    echo "Error: Invalid option: $1"
    show_correct_sintax
    exit 1
}

validate_argument(){
    return 0
}


validate_requirements(){
    if [[ $# -eq 0 ]]; then
        for cmd in aws psql; do
            if ! command -v $cmd &> /dev/null; then
                echo "Error: $cmd is not installed."
                exit 1
            fi
        done
    fi
}


validate_requirements(){
    local requirements=(
        "aws"
    )

    if [[ $# -eq 0 ]]; then
        for cmd in "${requirements[@]}"; do
            if ! command -v $cmd &> /dev/null; then
                echo "Error: $cmd is not installed."
                exit 1
            fi
        done
    fi
}

load_environments(){
    # -------------------------------------------
    # Load existing config if file exists
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
    fi

    # -------------------------------------------
    # Prompt for global environment variables
    # Load global values from file if they exist
    declare -gA GLOBAL
    if [ -n "$GLOBAL_AWS_REGION" ]; then
        GLOBAL[AWS_REGION]="$GLOBAL_AWS_REGION"
    fi
    # Prompt for global variables
    for i in "${GLOBAL_ENVS_ARRAY[@]}"; do
        current_value="${GLOBAL[$i]}"

        prompt_msg="Enter value for $i"
        if [ -n "$current_value" ]; then
            prompt_msg="$prompt_msg [$current_value]"
        fi

        read -p "$prompt_msg: " input_value

        if [ -n "$input_value" ]; then
            GLOBAL[$i]="$input_value"
        fi
    done

    # -------------------------------------------
    # Save current values to the config file
    > "$CONFIG_FILE"

    for i in "${GLOBAL_ENVS_ARRAY[@]}"; do
        echo "export GLOBAL_$i=\"${GLOBAL[$i]}\"" >> "$CONFIG_FILE"
    done

    # -------------------------------------------
    # Set restrictive permissions
    chmod 600 "$CONFIG_FILE"
}


get_id(){
    local instance_name="$1"
    local resp
    validate_requirements
    load_environments
    resp=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$instance_name" --query 'Reservations[*].Instances[*].InstanceId' --output text)
    echo ""
    echo $resp
    echo ""
}

get_name(){
    local instance_id="$1"
    local resp
    validate_requirements
    load_environments
    resp=$(aws ec2 describe-instances --instance-ids "$instance_id" --query 'Reservations[*].Instances[*].Tags[?Key==`Name`].Value' --output text)
    echo ""
    echo $resp
    echo ""
}

ssm_connect(){
    local instance_name="$1"
    local instance_id
    validate_requirements
    load_environments
    
    instance_id=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$instance_name" --query 'Reservations[*].Instances[*].InstanceId' --output text)
    
    aws ssm start-session --target "$instance_id"
}

reset_environment(){
    > "$CONFIG_FILE"

    for i in "${GLOBAL_ENVS_ARRAY[@]}"; do
        unset "GLOBAL_$i"
    done

    for i in "${RDS_ENVS_ARRAY[@]}"; do
        unset "RDS_$i"
    done
    echo "Environment variables have been reset."
}




# ===============================================
# init script
# ===============================================
initialize_script(){
    validate_option $1
    validate_argument $2

    case $1 in
        "--get-id")
            get_id $2
            ;;
        "--get-name")
            get_name $2
            ;;
        "--ssm-connect")
            ssm_connect $2
            ;;
        "--reset-env")
            reset_environment
            ;;
    esac

    exit 0
}
initialize_script $@

