#!/bin/bash

# ===============================================
# Global Configuration
# ===============================================
CONFIG_FILE="$HOME/.prospermedical_tools_config"


# Top-level environment variables
declare -a GLOBAL_ENVS_ARRAY=(
    "AWS_REGION"
)

# RDS environment variables
declare -a RDS_ENVS_ARRAY=(
    "CLUSTER_ENDPOINT"
    "PORT"
    "DATABASE"
    "USERNAME"
)



# ===============================================
# Processes
# ===============================================
show_correct_sintax(){
    echo "Usage: rdst [OPTION] [ARGUMENT]"
    echo ""
    echo "Options:"
    echo "  --connect          Connect to Aurora PostgreSQL database."
    echo "  --get-token        Generate and display a new authentication token."
    echo "  --show-token       Display the current authentication token."
    echo "  --reset-env        Reset all stored environment variables."
    echo ""
    echo "Arguments:"
    echo "  --novalidate       Skip validation of required tools [aws-cli, psql]."
    echo ""
}

validate_option(){
    local valid_options=(
        "--connect"
        "--get-token"
        "--show-token"
        "--reset-env"
    )

    for opt in "${valid_options[@]}"; do
        if [[ $opt = $1 ]]; then
            return 0
        fi
    done

    echo "Error: Invalid option: $1"
    show_correct_sintax
    exit 1
}

validate_argument(){
    local valid_args=(
        "--novalidate"
    )

    if [[ -z $1 ]]; then
        return 0
    fi

    for arg in "${valid_args[@]}"; do
        if [[ $arg = $1 ]]; then
            return 0
        fi
    done

    echo "Error: Invalid argument: $1"
    show_correct_sintax
    exit 1
}


validate_requirements(){
    local requirements=(
        "aws"
        "psql"
    )

    if [[ $# -eq 0 ]]; then
        for cmd in "${requirements[@]}"; do
            if ! command -v $cmd &> /dev/null; then
                echo "Error: $cmd is not installed."
                exit 1
            fi
        done
    fi
}

load_environments(){
    # -------------------------------------------
    # Load existing config if file exists
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
    fi

    # -------------------------------------------
    # Prompt for global environment variables
    # Load global values from file if they exist
    declare -gA GLOBAL
    if [ -n "$GLOBAL_AWS_REGION" ]; then
        GLOBAL[AWS_REGION]="$GLOBAL_AWS_REGION"
    fi
    # Prompt for global variables
    for i in "${GLOBAL_ENVS_ARRAY[@]}"; do
        current_value="${GLOBAL[$i]}"

        prompt_msg="Enter value for $i"
        if [ -n "$current_value" ]; then
            prompt_msg="$prompt_msg [$current_value]"
        fi

        read -p "$prompt_msg: " input_value

        if [ -n "$input_value" ]; then
            GLOBAL[$i]="$input_value"
        fi
    done

    # -------------------------------------------
    # Load RDS values from file if they exist
    # Load rds values from file if they exist
    declare -gA RDS
    if [ -n "$RDS_CLUSTER_ENDPOINT" ]; then
        RDS[CLUSTER_ENDPOINT]="$RDS_CLUSTER_ENDPOINT"
    fi
    if [ -n "$RDS_PORT" ]; then
        RDS[PORT]="$RDS_PORT"
    fi
    if [ -n "$RDS_DATABASE" ]; then
        RDS[DATABASE]="$RDS_DATABASE"
    fi
    if [ -n "$RDS_USERNAME" ]; then
        RDS[USERNAME]="$RDS_USERNAME"
    fi
    # Prompt for RDS variables
    for i in "${RDS_ENVS_ARRAY[@]}"; do
        current_value="${RDS[$i]}"

        prompt_msg="Enter value for $i"
        if [ -n "$current_value" ]; then
            prompt_msg="$prompt_msg [$current_value]"
        fi

        read -p "$prompt_msg: " input_value

        if [ -n "$input_value" ]; then
            RDS[$i]="$input_value"
        fi
    done

    # -------------------------------------------
    # Save current values to the config file
    > "$CONFIG_FILE"

    for i in "${GLOBAL_ENVS_ARRAY[@]}"; do
        echo "export GLOBAL_$i=\"${GLOBAL[$i]}\"" >> "$CONFIG_FILE"
    done

    for i in "${RDS_ENVS_ARRAY[@]}"; do
        echo "export RDS_$i=\"${RDS[$i]}\"" >> "$CONFIG_FILE"
    done

    # -------------------------------------------
    # Set restrictive permissions
    chmod 600 "$CONFIG_FILE"
}



connect_to_aurora_db(){
    validate_requirements $1
    load_environments
    psql -h "${RDS[CLUSTER_ENDPOINT]}" -p "${RDS[PORT]}" -U "${RDS[USERNAME]}" "${RDS[DATABASE]}"
}

get_new_token(){
    local resp
    validate_requirements $1
    load_environments
    resp="$(aws rds generate-db-auth-token --hostname ${RDS[CLUSTER_ENDPOINT]} --port ${RDS[PORT]} --region ${GLOBAL[AWS_REGION]} --username ${RDS[USERNAME]})"
    echo ""
    echo $resp
    echo ""
}

show_current_token(){
    echo "Current authentication token:"
    echo $PGPASSWORD
    echo ""
}

reset_environment(){
    > "$CONFIG_FILE"

    for i in "${GLOBAL_ENVS_ARRAY[@]}"; do
        unset "GLOBAL_$i"
    done

    for i in "${RDS_ENVS_ARRAY[@]}"; do
        unset "RDS_$i"
    done
    echo "Environment variables have been reset."
}




# ===============================================
# init script
# ===============================================
initialize_script(){
    validate_option $1
    validate_argument $2

    case $1 in
        "--connect")
            connect_to_aurora_db $2
            ;;

        "--get-token")
            get_new_token $2
            ;;

        "--show-token")
            show_current_token
            ;;

        "--reset-env")
            reset_environment
            ;;
    esac

    exit 0
}
initialize_script $@

